/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Image;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Product;

/**
 *
 * @author hp
 */
public class ProductEditView extends javax.swing.JFrame {

    String imgaeURL = "";

    /**
     * Creates new form ProductEditView
     */
    public ProductEditView() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtImageURL.setVisible(false);
        txtID.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        txtImageURL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtProductCode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtImPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtExPrice = new javax.swing.JTextField();
        messCode = new javax.swing.JLabel();
        messName = new javax.swing.JLabel();
        messNum = new javax.swing.JLabel();
        messIm = new javax.swing.JLabel();
        messEx = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        btnImage = new javax.swing.JButton();
        txtImage = new javax.swing.JLabel();
        txtMessage = new javax.swing.JLabel();
        btnTransport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Sản Phẩm ");
        setResizable(false);

        jLabel2.setText("Tên Sản phẩm");

        jLabel3.setText("Số lượng");

        txtID.setEnabled(false);

        jLabel4.setText("Mã sản phẩm");

        txtProductCode.setEnabled(false);

        jLabel5.setText("Giá nhập");

        jLabel6.setText("Giá xuất");

        messCode.setForeground(new java.awt.Color(255, 0, 51));

        messName.setForeground(new java.awt.Color(255, 0, 0));

        messNum.setForeground(new java.awt.Color(255, 0, 51));

        messIm.setForeground(new java.awt.Color(255, 0, 51));

        messEx.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtImageURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(261, 261, 261))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                    .addComponent(txtExPrice)
                                    .addComponent(txtImPrice))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(messCode)
                                .addComponent(messName)
                                .addComponent(messNum, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(messIm)
                            .addComponent(messEx, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtImageURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messCode))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messNum))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(messIm))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtExPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messEx))
                .addGap(17, 17, 17))
        );

        btnDelete.setText("Xóa");

        btnChange.setText("Cập nhật");

        btnImage.setText("Chọn ảnh");
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });

        txtMessage.setForeground(new java.awt.Color(255, 0, 51));

        btnTransport.setText("Vận chuyển");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnDelete)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(txtImage, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnImage)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnTransport)
                .addGap(18, 18, 18)
                .addComponent(btnChange)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtImage, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImage)
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(btnChange)
                            .addComponent(btnTransport))))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        try {
            JFileChooser f = new JFileChooser("D:\\Java_Swing\\tonghop\\src\\image");
            f.setDialogTitle("Mở ảnh");
            f.showOpenDialog(null);
            File ftenAnh = f.getSelectedFile();
            imgaeURL = ftenAnh.getAbsolutePath();
            txtImageURL.setText(imgaeURL);
            if (imgaeURL != null) {
                txtImage.setIcon(resizeImage(String.valueOf(imgaeURL)));
                System.out.println(imgaeURL);
            } else {
                showMessage("Bạn chưa chọn ảnh");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }    }//GEN-LAST:event_btnImageActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnImage;
    private javax.swing.JButton btnTransport;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel messCode;
    private javax.swing.JLabel messEx;
    private javax.swing.JLabel messIm;
    private javax.swing.JLabel messName;
    private javax.swing.JLabel messNum;
    private javax.swing.JTextField txtExPrice;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtImPrice;
    private javax.swing.JLabel txtImage;
    private javax.swing.JTextField txtImageURL;
    private javax.swing.JLabel txtMessage;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtProductCode;
    // End of variables declaration//GEN-END:variables
    public void addEditProductListiener(ActionListener listener) {
        btnChange.addActionListener(listener);
    }

    public void addDeleleProductListiener(ActionListener listener) {
        btnDelete.addActionListener(listener);
    }
    
    public void addGoToTransportListiener(ActionListener listener){
        btnTransport.addActionListener(listener);
    }
    
    public void showDetailProduct(Product p) {

        txtMessage.setText("");

        txtID.setText(p.getId() + "");
        txtProductCode.setText(p.getProductCode());
        txtName.setText(p.getName());
        txtNumber.setText(p.getQuantity() + "");
        txtImPrice.setText(p.getImPrice() + "");
        txtExPrice.setText(p.getExPrice() + "");
        txtImage.setIcon(resizeImage(p.getImage()));
        txtImageURL.setText(p.getImage());
    }

    public Product getProductData() {
        int id = Integer.parseInt(txtID.getText());
        String name = txtName.getText();
        String imgURL = txtImageURL.getText();
        String code = txtProductCode.getText();
        int imPrice = 0;
        int exPrice = 0;
        int quantity = 0;
        try {
            quantity = Integer.parseInt(txtNumber.getText());
            if (quantity <= 0) {
                throw new Exception();
            }
            txtMessage.setText("");
        } catch (Exception ex) {
            txtMessage.setText("Vui lòng nhập số lượng là 1 số nguyên dương !");
            return null;
        }

        try {
            imPrice = Integer.parseInt(txtImPrice.getText());
            if (imPrice <= 0) {
                throw new Exception();
            }
            txtMessage.setText("");
        } catch (Exception ex) {
            txtMessage.setText("Vui lòng nhập giá nhập là 1 số nguyên dương !");
            return null;
        }

        try {
            exPrice = Integer.parseInt(txtExPrice.getText());
            if (exPrice <= 0) {
                throw new Exception();
            }
            txtMessage.setText("");
        } catch (Exception ex) {
            txtMessage.setText("Vui lòng nhập giá suất là 1 số nguyên dương !");
            return null;
        }

        if (imPrice >= exPrice) {
            showMessage("Lưu ý : Giá nhập không thể lớn hơn giá suất");
            return null;
        }

        if (code.isEmpty()) {
            txtMessage.setText("Vui lòng nhập mã sản phẩm");
            return null;
        } else {
            txtMessage.setText("");
        }
        if (name.isEmpty()) {
            txtMessage.setText("Vui lòng nhập tên sản phẩm");
            return null;
        } else {
            txtMessage.setText("");
        }
        if (imgURL.isEmpty()) {
            txtMessage.setText("Vui lòng chọn ảnh");
            return null;
        } else {
            txtMessage.setText("");
        }
        return new Product(id, code, name, quantity, imgURL, imPrice, exPrice);
    }

    public int getProductId() {
        return Integer.parseInt(txtID.getText());
    }

    public void showMessage(String mess) {
        JOptionPane.showMessageDialog(this, mess);
    }

    public ImageIcon resizeImage(String imagePath) {
        ImageIcon myImage = new ImageIcon(imagePath);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(txtImage.getWidth(), txtImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

}
